// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { Application } from "@hotwired/stimulus";
import { Dropdown, Modal } from "tailwindcss-stimulus-components";
import Notification from "stimulus-notification";

const application = Application.start();

application.register("notification", Notification);
application.register("dropdown", Dropdown);
application.register("modal", Modal);

const controllerFiles = require.context(".", true, /_controller\.js$/);
controllerFiles.keys().forEach((filename) => {
  const controllerName = filename
    .replace("./", "")
    .replace("_controller.js", "")
    .replace(/_/g, "-");
  const controller = controllerFiles(filename).default;
  application.register(controllerName, controller);
});

application.debug = false;
window.Stimulus = application;

export { application };
